services:
  financeTracker.postgers:
    container_name: financeTracker.postgers
    image: postgres:16
    environment:
      - POSTGRES_DB=financeDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
